In [1]:
## Les bibliothèques nécessaires
import numpy as np
from sklearn.datasets import make_blobs

C:\Users\lenovo\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
centers=[[0,0],[3,3]]
data,true_labels=make_blobs(centers=centers,n_samples=10)

In [4]:
def cluster(data,true_labels):
    cluster=[[] for _ in range(2)]
    for i in range(data.shape[0]):
        cluster[true_labels[i]].append(data[i])
    return cluster

In [5]:
cluster(data,true_labels)

[[array([ 0.32102952, -2.03352205]),
  array([2.11374034, 0.38195696]),
  array([-0.37708521, -0.97022268]),
  array([-0.58285864, -0.96649873]),
  array([-2.00954157,  0.87615448])],
 [array([4.62297107, 3.22452531]),
  array([2.08961351, 3.47872992]),
  array([4.11190271, 2.61195011]),
  array([2.47471994, 3.54021462]),
  array([4.00318097, 3.38311814])]]

In [8]:
from scipy.spatial import distance
def inertie_intra_class(cluster):
    n=0
    inertie=0
    for cl in cluster:
        s=0
        for x in cl:
            for y in cl:
                s+=distance.euclidean(x,y)**2
        n=n+len(cl)
        inertie+=s/(2*len(cl))
    print(n)
    return inertie/n

In [ ]:
def intra_clas(cluster):
    i=0
    for cl in cluster:
        ic=0
        for x in cl:
            ic=ic+distance.euclidean(x,np.mean(cl,axis=0))**2
        i=i+ic/len(cl)
    return i/n

In [9]:
inertie_intra_class(cluster(data,true_labels))

10


1.9970270253013118

In [10]:
## Inertie inter-classe
def inertie_inter_class(cluster,g):
    n=0
    inertie=0
    for cl in cluster:
        c=np.mean(cl,axis=0)
        print(c)
        inertie+=len(cl)*distance.euclidean(c,g)**2
        n+=len(cl)
    return inertie/n

In [15]:
inertie_inter_class(cluster(data,true_labels),np.mean(data,axis=0))
#print(np.mean(data,axis=0))

[-0.10694311 -0.5424264 ]
[3.46047764 3.24770762]


6.772901680353544

In [13]:
def inertie_totale(data):
    g=np.mean(data,axis=0)
    s=0
    for x in data:
        s+=distance.euclidean(x,g)**2
    return s/data.shape[0]

In [14]:
inertie_totale(data)

8.769928705654854

In [16]:
inertie_inter_class(cluster(data,true_labels),np.mean(data,axis=0))+inertie_intra_class(cluster(data,true_labels))

[-0.10694311 -0.5424264 ]
[3.46047764 3.24770762]
10


8.769928705654856