In [22]:
import numpy as np
from sklearn.datasets import make_blobs
from scipy.spatial.distance import cdist

In [23]:
#centers = [[1, 2],[7, 8]]
centers = [[0, 0],[1, 1]]
data, labels = make_blobs(n_samples=10, centers=centers) 
# n_samples: number of samples, centers: number of centers

In [24]:
def cluster(data,true_labels):
    cluster=[[] for _ in range(2)]
    for i in range(data.shape[0]):
        cluster[true_labels[i]].append(data[i])
    return cluster

In [25]:
cluster(data,labels)

[[array([ 0.47832166, -0.82321924]),
  array([-1.64056009, -0.04785039]),
  array([-0.35029624, -0.58508639]),
  array([-0.68703051,  1.07711928]),
  array([-0.04962901,  0.61314939])],
 [array([1.08612315, 0.61640344]),
  array([1.97791662, 2.73058925]),
  array([2.34248557, 2.62098988]),
  array([1.56510296, 1.35288203]),
  array([2.10057826, 0.84877808])]]

In [26]:
def inertieIntra_Class(cluster):
    n=0
    inertie=0
    for c1 in cluster:
        s=0
        for x in c1:
            for y in c1:
                s+=cdist(x.reshape(1,-1),y.reshape(1,-1))**2
        n=n+len(c1)
        inertie+=s/(2*len(c1))
    print(n)
    return inertie/n

In [27]:
def intra_class(cluster):
    i=0
    for c1 in cluster:
        s=0
        for x in c1:
            for y in c1:
                s+=s+cdist(x.reshape(1,-1),y.reshape(1,-1))**2
        i+=s/(2*len(c1))
    return i/len(cluster)

In [ ]:
def affectation(data,centers):
    labels=[]
    groups=[[] for _ in range(len(centers))]
    for x in data:
        d1=cdist(x.reshape(1,-1),centers[0].reshape(1,-1))
        d2=cdist(x.reshape(1,-1),centers[1].reshape(1,-1))
        if d1<d2:
            labels.append(0)
        else:
            labels.append(1)
    return labels


In [ ]:
def mise_a_jour(data,labels):
    cluster=[[] for _ in range(2)]
    for i in range(data.shape[0]):
        cluster[labels[i]].append(data[i])
    centers=[]
    for c1 in cluster:
        centers.append(np.mean(c1,axis=0))
    return centers