In [5]:
## importer les packages
import numpy as np
import pandas as ps

In [6]:
### Importer la data
df1=ps.read_csv('Youtube01-Psy.csv')
df2=ps.read_csv('Youtube02-KatyPerry.csv')
df3=ps.read_csv('Youtube05-Shakira.csv')
df4=ps.read_csv('Youtube04-Eminem.csv')
### Concatener les datas en corpus
corpus=ps.concat([df1,df2,df3,df4])
print(corpus.shape)

(1518, 5)


In [7]:
print(corpus.shape)
corpus.head()

(1518, 5)


COMMENT_ID            AUTHOR  \
0  LZQPQhLyRh80UYxNuaDWhIGQYNQ96IuCg-AYWqNPjpU         Julius NM   
1  LZQPQhLyRh_C2cTtd9MvFRJedxydaVW-2sNg5Diuo4A       adam riyati   
2  LZQPQhLyRh9MSZYnf8djyk0gEF9BHDPYrrK-qCczIY8  Evgeny Murashkin   
3          z13jhp0bxqncu512g22wvzkasxmvvzjaz04   ElNino Melendez   
4          z13fwbwp1oujthgqj04chlngpvzmtt3r3dw            GsMega   

                  DATE                                            CONTENT  \
0  2013-11-07T06:20:48  Huh, anyway check out this you[tube] channel: ...   
1  2013-11-07T12:37:15  Hey guys check out my new channel and our firs...   
2  2013-11-08T17:34:21             just for test I have to say murdev.com   
3  2013-11-09T08:28:43   me shaking my sexy ass on my channel enjoy ^_^    
4  2013-11-10T16:05:38            watch?v=vtaRGgvGtWQ   Check this out .   

   CLASS  
0      1  
1      1  
2      1  
3      1  
4      1

In [11]:
print(corpus.CONTENT.iloc[0])
print(corpus.CLASS.iloc[0])

Huh, anyway check out this you[tube] channel: kobyoshi02
1


In [12]:
### data equilibrée
corpus.CLASS.value_counts()

1    769
0    749
Name: CLASS, dtype: int64

In [13]:
#### Partager la data en data d'apprentissage et data de teste
from sklearn.model_selection import train_test_split
X_appr,X_test,y_appr,y_test=train_test_split(corpus['CONTENT'],corpus['CLASS'],test_size=0.25)
print(X_appr.shape)
print(X_appr.iloc[1])
print(y_appr.iloc[1])

(1138,)
Can we reach 3 billion views by December 2014? 
0


In [14]:
# import and instantiate the vectorizer
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
vectorizer = CountVectorizer()
#vectorizer1=TfidfVectorizer()

In [15]:
## créer la matrice de données d'apprentissage
X_appr_vect= vectorizer.fit_transform(X_appr)

In [16]:
X_appr_vect.shape

(1138, 3446)

In [17]:
print(X_appr_vect)

  (0, 3014)	1
  (0, 1367)	1
  (0, 2785)	1
  (0, 1871)	1
  (0, 164)	1
  (0, 2251)	1
  (0, 2994)	2
  (0, 2240)	1
  (0, 3302)	1
  (0, 2288)	1
  (0, 1718)	1
  (0, 1445)	1
  (1, 701)	1
  (1, 3273)	1
  (1, 2487)	1
  (1, 592)	1
  (1, 3205)	1
  (1, 687)	1
  (1, 966)	1
  (1, 108)	1
  (2, 3014)	1
  (2, 756)	1
  (2, 2265)	1
  (2, 2351)	1
  (2, 2233)	1
  :	:
  (1134, 3311)	1
  (1134, 2773)	1
  (1134, 2007)	1
  (1134, 1750)	1
  (1134, 2407)	1
  (1134, 1217)	1
  (1134, 558)	1
  (1134, 1656)	1
  (1134, 204)	1
  (1134, 2086)	1
  (1135, 2233)	1
  (1135, 1999)	1
  (1135, 1320)	1
  (1135, 1688)	1
  (1135, 586)	1
  (1136, 1609)	1
  (1136, 3002)	1
  (1136, 2633)	1
  (1136, 3055)	1
  (1136, 239)	1
  (1136, 3032)	1
  (1137, 3039)	1
  (1137, 2128)	1
  (1137, 2882)	1
  (1137, 1274)	1


In [18]:
print(X_appr_vect.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
vectorizer.get_feature_names_out()

array(['00', '000', '002', ..., 'ｔｈｉｓ', 'ｕｓｒ', 'ｗｗｗ'], dtype=object)

In [20]:
### Modèle de machine learning
from sklearn.ensemble import RandomForestClassifier
## Définir le modèle de ML
rf=RandomForestClassifier()
### Entrainer le modèle
rf_app=rf.fit(X_appr_vect,y_appr)
### Evaluation : matrice de confusion et accuracy
from sklearn import metrics
cm=metrics.confusion_matrix(y_appr,rf.predict(X_appr_vect))
print(cm)
rf_app.score(X_appr_vect,y_appr)

[[562   0]
 [  0 576]]


1.0

In [21]:
### Tester le modèle 
X_test_vec=vectorizer.fit_transform(X_test)
cm=metrics.confusion_matrix(y_test,rf.predict(X_test_vec))
print(cm)
rf_app.score(X_test_vec,y_test)


ValueError: X has 1577 features, but RandomForestClassifier is expecting 3446 features as input.

In [24]:
X_vector=vectorizer.fit_transform(corpus['CONTENT'])
print(X_vector.shape)
X_appr,X_test,y_appr,y_test=train_test_split(X_vector,corpus['CLASS'],test_size=0.25)

(1518, 4112)


In [23]:
X_appr.shape

(1138, 4112)

In [59]:
### Modèle de machine learning
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf_app=rf.fit(X_appr,y_appr)
print(rf_app.score(X_appr,y_appr))
rf_app.score(X_test,y_test)

1.0


0.9710526315789474

In [16]:
X_test.shape

(380, 4112)

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,rf_app.predict(X_test)))

              precision    recall  f1-score   support

           0       0.92      0.98      0.95       194
           1       0.98      0.91      0.95       186

    accuracy                           0.95       380
   macro avg       0.95      0.95      0.95       380
weighted avg       0.95      0.95      0.95       380



In [18]:
from sklearn.model_selection import cross_val_score
cross_val_score(rf,X_appr,y_appr,cv=7)

array([0.96319018, 0.95705521, 0.91411043, 0.96932515, 0.9382716 ,
       0.95061728, 0.94444444])

In [19]:
np.mean(cross_val_score(rf,X_appr,y_appr,cv=5))

0.9525542932220418

In [20]:
### Creer de modele d'arbre de décision
from sklearn.tree import DecisionTreeClassifier
h=DecisionTreeClassifier()
### Apprentissage
h=h.fit(X_appr,y_appr)

In [21]:
from sklearn.metrics import confusion_matrix
mc=confusion_matrix(y_test,h.predict(X_test))
mc

array([[188,   6],
       [ 13, 173]], dtype=int64)

In [22]:
h.score(X_test,y_test)

0.95

In [23]:
#### Partie 2
tfidf=TfidfVectorizer()
X_vect1= tfidf.fit_transform(corpus)

In [ ]:
#### 